distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Sun Jun  7 14:19:58 2020"
installation_id: "76b560ef-1bdb-46ec-bc53-5e34c88586b9"
rime_version: 1.5.3